version: '3.8'

services:
  mysql-db:
    image: my`sql:8.0
    container_name: quiz_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: quiz_platform
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: